# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'bcrypt', '~> 3.1'
gem 'dotenv', groups: %i[development test]
gem 'jwt', '~> 2.8'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'
gem 'rake'
gem 'sinatra', '~> 4.0'
gem 'sinatra-activerecord'
gem 'sinatra-contrib', '~> 4.0'
gem 'sqlite3'
